# Generated by Django 6.1 on 2026-08-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_weight', models.FloatField(default=0.7, help_text='과제 성취도 비중')),
                ('sincerity_weight', models.FloatField(default=0.3, help_text='성실성(제출률) 비중')),
                ('individual_ratio', models.FloatField(default=0.7, help_text='성취도 내 개인 과제 비중')),
                ('team_ratio', models.FloatField(default=0.3, help_text='성취도 내 팀 과제 비중')),
                ('optional_ratio', models.FloatField(default=0.6, help_text='성취도 내 선택 과제 비중')),
                ('required_ratio', models.FloatField(default=0.4, help_text='성취도 내 필수 과제 비중')),
                ('required_floor', models.PositiveSmallIntegerField(default=40, help_text='필수 과제 제출 시 최저 보장 점수')),
                ('optional_floor', models.PositiveSmallIntegerField(default=20, help_text='선택 과제 제출 시 최저 보장 점수')),
                ('required_miss_penalty', models.PositiveSmallIntegerField(default=10, help_text='필수 과제 미제출 시 부여 점수')),
                ('weight_high', models.FloatField(default=1.5)),
                ('weight_mid', models.FloatField(default=1.0)),
                ('weight_low', models.FloatField(default=0.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '성적 집계 정책',
                'verbose_name_plural': '성적 집계 정책',
                'db_table': 'grading_policy',
            },
        ),
    ]
