# Generated by Django 6.1 on 2026-09-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.BigIntegerField(help_text='AX rounds_evaluationround.id')),
                ('round_title', models.CharField(blank=True, help_text='스냅샷', max_length=200)),
                ('student_id', models.IntegerField(help_text='accounts_user.id 참조, FK 아님')),
                ('student_name', models.CharField(blank=True, help_text='스냅샷', max_length=150)),
                ('total', models.FloatField(blank=True, help_text='최종 점수(0~100). AX2 전달값. None=산출 불가', null=True)),
                ('achievement', models.FloatField(blank=True, null=True)),
                ('sincerity', models.FloatField(blank=True, null=True)),
                ('team_included', models.BooleanField(default=False, help_text='팀 과제 점수 반영 여부 (팀 미편성이면 False)')),
                ('graded_count', models.PositiveSmallIntegerField(default=0)),
                ('ungraded_count', models.PositiveSmallIntegerField(default=0)),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='영역별 내역 (감사용)')),
                ('assignment_ids', models.JSONField(blank=True, default=list, help_text='집계 대상 과제 id')),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text='마감 시점 GradingPolicy')),
                ('closed_at', models.DateTimeField(help_text='마감/재마감 시각')),
                ('closed_by', models.IntegerField(help_text='마감한 튜터 accounts_user.id')),
            ],
            options={
                'db_table': 'round_score',
                'ordering': ['-closed_at', 'student_name'],
                'indexes': [models.Index(fields=['round_id'], name='round_score_round_idx')],
                'constraints': [models.UniqueConstraint(fields=('round_id', 'student_id'), name='round_score_round_student_uniq')],
            },
        ),
    ]
