# Generated by Django 6.1 on 2026-08-31 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_todo_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGithubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(help_text='accounts_user.id (FK 아님)', unique=True)),
                ('github_user_id', models.BigIntegerField()),
                ('github_login', models.CharField(max_length=100)),
                ('github_name', models.CharField(blank=True, max_length=200)),
                ('access_token_encrypted', models.TextField()),
                ('token_scope', models.CharField(blank=True, max_length=200)),
                ('repo_full_name', models.CharField(blank=True, help_text='최초 저장소 확보 후 캐시 (예: nelson/lms-assignments)', max_length=200)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'github_student_account',
            },
        ),
        migrations.CreateModel(
            name='SubmissionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', '대기'), ('SYNCED', '동기화됨'), ('FAILED', '실패'), ('NO_ACCOUNT', 'GitHub 미연결')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('committed_path', models.CharField(blank=True, max_length=500)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('is_finalized', models.BooleanField(default=False, help_text="마감 후 '최종 제출' 커밋까지 완료")),
                ('finalized_commit_sha', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_push', to='core.submission')),
            ],
            options={
                'db_table': 'github_submission_push',
                'indexes': [models.Index(fields=['state'], name='github_subm_state_9814de_idx')],
            },
        ),
    ]
