# Generated by Django 6.1 on 2026-09-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assignmentfile'),
        ('github_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorGithubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_id', models.IntegerField(help_text='accounts_user.id (FK 아님)', unique=True)),
                ('github_user_id', models.BigIntegerField()),
                ('github_login', models.CharField(max_length=100)),
                ('github_name', models.CharField(blank=True, max_length=200)),
                ('access_token_encrypted', models.TextField()),
                ('token_scope', models.CharField(blank=True, max_length=200)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'github_tutor_account',
            },
        ),
        migrations.CreateModel(
            name='FeedbackIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', '대기'), ('CREATED', '이슈 생성됨'), ('COMMENTED', '코멘트 추가됨'), ('SKIPPED', '대상 아님'), ('FAILED', '실패')], default='PENDING', max_length=12)),
                ('issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_url', models.URLField(blank=True)),
                ('feedback_hash', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_feedback_issue', to='core.submission')),
            ],
            options={
                'db_table': 'github_feedback_issue',
                'indexes': [models.Index(fields=['state'], name='github_feed_state_c1e140_idx')],
            },
        ),
    ]
