# Generated by Django 6.1 on 2026-08-27 03:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('is_required', models.BooleanField(default=True)),
                ('allow_late', models.BooleanField(default=True)),
                ('is_team', models.BooleanField(default=False, help_text='true=팀 과제, false=개인 과제')),
                ('weight_tier', models.CharField(choices=[('HIGH', '상'), ('MID', '중'), ('LOW', '하')], default='MID', max_length=10)),
                ('created_by', models.IntegerField(help_text='accounts_user.id 참조, FK 아님 (튜터)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='소프트 삭제. null=활성 상태, undo는 이 값 복구로 처리', null=True)),
            ],
            options={
                'db_table': 'assignment',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(help_text='accounts_user.id 참조, FK 아님')),
                ('content', models.CharField(max_length=500)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_date', models.DateField()),
                ('blog_link', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='수업 종료 후 튜터가 추가, nullable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.lecture')),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ['lesson_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FILE', '파일'), ('LINK', '링크')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField(blank=True, help_text='kind=FILE인 경우', null=True)),
                ('link_url', models.URLField(blank=True, help_text='kind=LINK인 경우', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.lesson')),
            ],
            options={
                'db_table': 'lesson_material',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, help_text='accounts_user.id 참조, 개인 과제인 경우', null=True)),
                ('team_id', models.IntegerField(blank=True, help_text='teams_team.id 참조, 팀 과제인 경우 (팀장만 제출)', null=True)),
                ('description', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False, help_text='EVALUATION 최초 저장 시 true, 재제출 차단')),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='0 to 100')),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='core.submission')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='AiEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='0 to 100')),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='core.submission')),
            ],
            options={
                'db_table': 'ai_evaluation',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PY', '.py'), ('IPYNB', '.ipynb'), ('OTHER', '그 외')], max_length=10)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='바이트 단위')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.submission')),
            ],
            options={
                'db_table': 'submission_file',
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student_id__isnull', False), ('team_id__isnull', True)), models.Q(('student_id__isnull', True), ('team_id__isnull', False)), _connector='OR'), name='submission_student_id_xor_team_id'),
        ),
    ]
