# Generated by Django 6.1 on 2026-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_editor_id',
            field=models.IntegerField(blank=True, help_text='accounts_user.id — 최초 제출/마지막 재제출을 수행한 사용자 (팀 과제 책임소재)', null=True),
        ),
    ]
