# Generated by Django 6.1 on 2026-08-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_penalty',
            field=models.PositiveSmallIntegerField(default=0, help_text='지각 제출 시 점수에서 차감할 점수 (0=감점 없음)'),
        ),
    ]
