# Generated by Django 6.1 on 2026-09-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_late_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='blog_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='예: 1부 개념, 2부 실습', max_length=200)),
                ('video_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='영상 재생 순서')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.lesson')),
            ],
            options={
                'db_table': 'lesson_video',
                'ordering': ['order', 'id'],
            },
        ),
    ]
