# Generated by Django 6.1 on 2026-09-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_lesson_blog_link_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FILE', '파일'), ('LINK', '링크')], max_length=10)),
                ('title', models.CharField(blank=True, help_text='비우면 파일명/URL 사용', max_length=200)),
                ('file_url', models.URLField(blank=True, help_text='kind=FILE')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='바이트')),
                ('link_url', models.URLField(blank=True, help_text='kind=LINK')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.assignment')),
            ],
            options={
                'db_table': 'assignment_file',
                'ordering': ['order', 'id'],
            },
        ),
    ]
